// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCev25lkkoe7548QCreUSMok5gqZSPhY4o',
    appId: '1:401828381959:web:3e44bcac8915e2ad0ef1a2',
    messagingSenderId: '401828381959',
    projectId: 'studymate-d4e94',
    authDomain: 'studymate-d4e94.firebaseapp.com',
    storageBucket: 'studymate-d4e94.firebasestorage.app',
    measurementId: 'G-NG21CDCM94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtLaZI8-syzuGWwdIlV7468H_Cuvm0JKs',
    appId: '1:401828381959:android:7c9b9d9067d8c5610ef1a2',
    messagingSenderId: '401828381959',
    projectId: 'studymate-d4e94',
    storageBucket: 'studymate-d4e94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCITcMUFhz4oZlhnFYrWvtk1QVjw0yZQQ',
    appId: '1:401828381959:ios:a0347d8bd7c9cc610ef1a2',
    messagingSenderId: '401828381959',
    projectId: 'studymate-d4e94',
    storageBucket: 'studymate-d4e94.firebasestorage.app',
    iosBundleId: 'com.example.studymate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCITcMUFhz4oZlhnFYrWvtk1QVjw0yZQQ',
    appId: '1:401828381959:ios:a0347d8bd7c9cc610ef1a2',
    messagingSenderId: '401828381959',
    projectId: 'studymate-d4e94',
    storageBucket: 'studymate-d4e94.firebasestorage.app',
    iosBundleId: 'com.example.studymate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCev25lkkoe7548QCreUSMok5gqZSPhY4o',
    appId: '1:401828381959:web:44d97bc14621e4640ef1a2',
    messagingSenderId: '401828381959',
    projectId: 'studymate-d4e94',
    authDomain: 'studymate-d4e94.firebaseapp.com',
    storageBucket: 'studymate-d4e94.firebasestorage.app',
    measurementId: 'G-J68299FCT3',
  );
}
